package sandbox

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"

	"github.com/Amitgb14/sandbox-cli/internal/config"
	"github.com/Amitgb14/sandbox-cli/internal/runtime"
)

// Name resolution for runtimes that cannot reach the engine's embedded DNS
// server (runtime.EmbeddedResolverUnreachable explains which, and why).
//
// The container gets a resolv.conf sandbox-cli **generates**, mounted read-only
// over /etc/resolv.conf. Three properties decided this shape over the two
// alternatives:
//
//   - It is not the host's /etc/resolv.conf. timezone.go argues that a name is a
//     string and a mount is another host path, and that rule holds here: what is
//     mounted is a file this tool wrote into its own state directory from values
//     read on the host, the same pattern as the generated managed-settings.json.
//     The host's own file is read and never exposed — it commonly contains search
//     domains that name an employer's internal network.
//   - It works in **every** network mode. Passing the addresses in an environment
//     variable for the root entrypoint to write was the obvious alternative, and
//     it is wrong: that entrypoint runs in allowlist mode only, so
//     `--runtime runsc --network default` would have stayed silently broken.
//   - A hostile project config cannot reach it. Choosing a container's resolver is
//     a redirection primitive — point every name at a resolver you control and the
//     allowlist resolves addresses of your choosing while looking entirely correct
//     — and `mounts` is already refused from a project .sandbox.yaml
//     (config/trust.go), so this inherits that refusal instead of needing a new
//     reserved name.
//
// Docker's embedded resolver also answers *container* names on the network. That
// is lost here, and it is not a cost worth mitigating: sandboxes reaching each
// other by name is what enable_icc=false exists to prevent.

// hostResolvers is a var for the same reason hostTimezone and hostPrimaryGID
// are: BuildSpec must produce the same spec on every machine, and this is one of
// the few inputs that genuinely differs per host.
var hostResolvers = readHostResolvers

// resolvConfTarget is the file the container reads to find its resolvers.
const resolvConfTarget = "/etc/resolv.conf"

// hostResolverMount generates the resolv.conf and returns the mount that carries
// it, or an error naming what could not be established.
//
// It refuses rather than proceeding when no usable resolver was found. The
// alternative is what happens today — a container that starts, looks healthy and
// resolves nothing — and an agent reporting that every request failed is a much
// worse diagnostic than a refusal that names the file to look at.
func hostResolverMount(runtimeName string) (runtime.Mount, error) {
	root := config.ConfigRoot()
	if root == "" {
		return runtime.Mount{}, fmt.Errorf(
			"--runtime %s needs DNS resolvers supplied to the container, but the home "+
				"directory could not be determined, so there is nowhere to write them",
			runtimeName)
	}

	servers := hostResolvers()
	if len(servers) == 0 {
		return runtime.Mount{}, fmt.Errorf(
			"--runtime %s cannot use docker's embedded DNS server, and no usable resolver "+
				"was found in /etc/resolv.conf on this host (a loopback resolver such as "+
				"systemd-resolved's 127.0.0.53 cannot be reached from a container). The "+
				"container would resolve no names at all. Add a routable `nameserver` line "+
				"to /etc/resolv.conf, or run without --runtime %s",
			runtimeName, runtimeName)
	}

	path := filepath.Join(root, "resolv.conf")
	if err := writeResolvConf(path, servers); err != nil {
		return runtime.Mount{}, fmt.Errorf("writing %s: %w", path, err)
	}
	return runtime.Mount{Source: path, Target: resolvConfTarget, RO: true}, nil
}

// writeResolvConf writes the file atomically, because concurrent runs — a fleet,
// or two terminals — share this one path. The content is identical for all of
// them, so a rename race is harmless; a half-written file read by a container
// starting at that moment would not be.
func writeResolvConf(path string, servers []string) error {
	var b strings.Builder
	b.WriteString("# Generated by sandbox-cli. Do not edit; rewritten on every run.\n")
	b.WriteString("# The engine's embedded resolver is unreachable on this runtime, so the\n")
	b.WriteString("# host's own resolvers are used directly. See internal/sandbox/resolvers.go.\n")
	for _, s := range servers {
		b.WriteString("nameserver " + s + "\n")
	}
	// No `search` line, deliberately. Search domains come from the host's resolv.conf
	// and routinely name an internal network; the container has no use for them and
	// they would leak a fact about where the host sits.

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), "resolv.conf.*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(b.String()); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	// World-readable: the container reads this as the sandbox user, and unlike the
	// state directories there is nothing private in it — these are the addresses of
	// name servers, not credentials.
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// readHostResolvers returns the host's routable nameserver addresses, in the
// order /etc/resolv.conf lists them.
//
// Two classes are dropped, and both would produce a container that resolves
// nothing while looking correctly configured:
//
//   - **Loopback.** A host running systemd-resolved lists 127.0.0.53, and a
//     container's 127.0.0.53 is its own loopback, where nothing is listening.
//     This is also what makes the docker case self-correcting: 127.0.0.11 is
//     loopback too, so a resolv.conf that has already been rewritten by an engine
//     contributes nothing here.
//   - **Anything that is not an IP address.** resolv.conf takes addresses, not
//     names; a name here could only come from a malformed file, and resolving it
//     would need the resolver we are trying to configure.
func readHostResolvers() []string {
	data, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return nil
	}
	return parseResolvers(string(data))
}

// parseResolvers is the parsing half, split out so it can be tested against the
// shapes real hosts produce without one of them having to be the test machine.
func parseResolvers(data string) []string {
	var out []string
	seen := map[string]bool{}
	for _, line := range strings.Split(data, "\n") {
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if i := strings.IndexByte(line, ';'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "nameserver" {
			continue
		}
		ip := net.ParseIP(fields[1])
		if ip == nil || ip.IsLoopback() || ip.IsUnspecified() || ip.IsLinkLocalUnicast() {
			continue
		}
		if seen[fields[1]] {
			continue
		}
		seen[fields[1]] = true
		out = append(out, fields[1])
	}
	return out
}
