import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next on every build and its triple-slash
    // reference is not ours to rewrite.
    ignores: [".next/**", "node_modules/**", "out/**", "next-env.d.ts"],
  },
  {
    // The vendored shadcn/ui primitives are upstream code, kept editable but
    // not held to this app's lint rules — the point of copy-in components is
    // that they can be re-pulled from the registry.
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },
];

export default eslintConfig;
